TOPDIR ?= ../..
include $(TOPDIR)/.config

$(SPOTLIGHT_SUPPORT)_SRC += services/spotlight/spotlight.c
$(SPOTLIGHT_SUPPORT)_SRC += services/spotlight/spotlight_ecmd.c

#########################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
